# -------------------------------------------------- #
# This file is autogenerated by pioasm; do not edit! #
# -------------------------------------------------- #

import rp2
from machine import Pin
# ----------- #
# pio_encoder #
# ----------- #

@rp2.asm_pio(autopush=False, autopull=False, fifo_join=rp2.PIO.JOIN_NONE, in_shiftdir=rp2.PIO.SHIFT_LEFT, out_shiftdir=rp2.PIO.SHIFT_RIGHT)
def pio_encoder():
    wrap_target()
    jmp("17")                             # 0
    jmp("27")                             # 1
    jmp("29")                             # 2
    jmp("17")                             # 3
    jmp("29")                             # 4
    jmp("17")                             # 5
    jmp("17")                             # 6
    jmp("27")                             # 7
    jmp("27")                             # 8
    jmp("17")                             # 9
    jmp("17")                             # 10
    jmp("29")                             # 11
    jmp("17")                             # 12
    jmp("29")                             # 13
    jmp("27")                             # 14
    jmp("17")                             # 15
    in_(pins, 2)                          # 16
    label("17")
    mov(y, isr)                           # 17
    mov(isr, x)                           # 18
    push(noblock)                         # 19
    pull(noblock)                         # 20
    mov(x, osr)                           # 21
    mov(isr, y)                           # 22
    mov(osr, isr)                         # 23
    out(isr, 2)                           # 24
    in_(pins, 2)                          # 25
    mov(exec, isr)                        # 26
    label("27")
    jmp(x_dec, "28")                      # 27
    label("28")
    jmp("17")                             # 28
    label("29")
    mov(x, invert(x))                     # 29
    jmp(x_dec, "31")                      # 30
    label("31")
    mov(x, invert(x))                     # 31
    wrap()


